hospital_ASI/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [

    url(r'^', include('i_tracker.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

i_tracker/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^login/$', views.login, name='login'),
	url(r'^logout/$', views.logout, name='logout'),

	url(r'^$', views.home, name='home'),
	url(r'^table/$', views.home_table, name='home_table'),
	url(r'^issue/$', views.issue, name='issue'), #new issue
	url(r'^issue/(?P<issue_pk>\d+)/$', views.issue, name='issue'), #issue
	url(r'^issue/delete/(?P<issue_pk>\d+)/$', views.delete_issue, name="delete_issue"), #delete issue

	url(r'^issue/(?P<issue_pk>\d+)/comment/$', views.comment, name='comment'), #new comment for an issue
	url(r'^issue/(?P<issue_pk>\d+)/comment/delete/(?P<comment_pk>\d+)/$', views.delete_comment, name='delete_comment'), #delete comment

	url(r'^get/users/profile/$', views.get_users_profile, name='get_users_profile'),
]

i_tracker/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Profile(models.Model):
	name 		= models.CharField(max_length=100)

	def __str__(self):              # __unicode__ on Python 2
		return self.name

class UserProfile(models.Model):
	user 		= models.ForeignKey(User)
	profile 	= models.ForeignKey(Profile)

class Priority(models.Model):
	name 		= models.CharField(max_length=30)

	def __str__(self):              # __unicode__ on Python 2
		return self.name

class State(models.Model):
	name 		= models.CharField(max_length=30)

	def __str__(self):              # __unicode__ on Python 2
		return self.name


class Category(models.Model):
	name 		= models.CharField(max_length=30)	
	description = models.TextField()

	def __str__(self):              # __unicode__ on Python 2
		return self.name

		
class Ticket(models.Model):
	name 		= models.CharField(max_length=100, blank=False)
	description = models.TextField(blank=False)
	dateraised 	= models.DateField(blank=True, null=True)
	datesolved 	= models.DateField(blank=True, null=True)
	priority 	= models.ForeignKey(Priority, on_delete=models.CASCADE, blank=False)
	creator 	= models.ForeignKey(User, on_delete=models.CASCADE, blank=False)
	categories 	= models.ManyToManyField(Category, related_name='ticket_categories', blank=False)
	user 		= models.ForeignKey(User, related_name='ticket_user', on_delete=models.CASCADE, default=0, blank=False)
	state	 	= models.ForeignKey(State, on_delete=models.CASCADE, blank=False)
	escalated 	= models.BooleanField(default=False)
	hidden		= models.BooleanField(default=False)

	def __str__(self):              # __unicode__ on Python 2
		return self.name

class Comment(models.Model):
	ticket 		= models.ForeignKey(Ticket, on_delete=models.CASCADE, blank=False)
	user 		= models.ForeignKey(User, on_delete=models.CASCADE, blank=False)
	description = models.TextField(blank=False)

i_tracker/forms.py
# -*- encoding: utf-8 -*-
from django.utils.datastructures import MultiValueDict, MergeDict
from bootstrap3_datetime.widgets import DateTimePicker
from django import forms
from .models import Ticket, Comment, Priority, Category, User, State

class LoginForm(forms.Form):
    username = forms.CharField(label='Usuario')
    password = forms.CharField(widget=forms.PasswordInput, label='Contraseña')

class TicketForm(forms.ModelForm):

	datesolved 	= forms.DateField(widget=DateTimePicker(options={"format": "DD/MM/YYYY"}), required=False, label='Solucionado')
	name 		= forms.CharField(max_length=100, label='Nombre')
	description = forms.CharField(widget=forms.Textarea(attrs={'rows':7}), label='Descripción')
	priority 	= forms.ModelChoiceField(queryset=Priority.objects.all(), label='Prioridad')
	categories 	= forms.ModelMultipleChoiceField(queryset=Category.objects.all(), label='Categorias')
	user 		= forms.ModelChoiceField(queryset=User.objects.all(), label='Asignado')
	escalated 	= forms.BooleanField(label='Escalar', initial=False, required=False)
	hidden	 	= forms.BooleanField(label='Archivar', initial=False, required=False)
	state	    = forms.ModelChoiceField(queryset=State.objects.all(), label='Estado', required=True)
	class Meta:
		model  = Ticket
		fields = ['datesolved', 'name', 'description', 'priority', 'categories', 'user', 'escalated', 'hidden', 'state']
		
class CommentForm(forms.ModelForm):
	
	description = forms.CharField(widget=forms.Textarea(attrs={'rows':5}), label='Comentar')

	class Meta:
		model = Comment
		fields = ['description']

i_tracker/views.py
from .forms import LoginForm, TicketForm, CommentForm
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.messages import get_messages 
from django.core import serializers 
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views.generic.edit import DeleteView # this is the generic view
from i_tracker.models import * 
from i_tracker.tables import TicketTable
import datetime

# LOGIN VIEW
def login(request):
	
	#log out if user logged
	if request.session:
		auth_logout(request)

	login_form = LoginForm(request.POST or None)

	if login_form.is_valid():
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)

		if user is not None:
			if user.is_active:
				auth_login(request, user)
				return redirect('home')
			else:
				return HttpResponse("Inactive user.")
		else:
			return redirect('login')

	context = {
		"LoginForm": LoginForm,
	}

	return render(request, "i_tracker/login.html", context)

# LOGOUT VIEW
@login_required(login_url='/login/')
def logout(request):
	auth_logout(request)
	context = {}
	return redirect('login')

# HOME VIEW
@login_required(login_url='/login/')
def home(request):

	session = request.session

	uid = session.get('_auth_user_id')

	issues = list(Ticket.objects.filter(user=uid))

	created_issues = list(Ticket.objects.filter(creator=uid))

	if request.user.is_superuser:

		escalated_issues = Ticket.objects.filter(escalated=True)
	else:

		escalated_issues = []
		
	context = {

		"session"          : session,
		"issues"           : issues,
		"created_issues"   : created_issues,
		"escalated_issues" : escalated_issues, 
	}
	return render(request, "i_tracker/home.html", context)

# TABLE VIEW
@login_required(login_url='/login/')
def home_table(request):

	session = request.session

	uid = session.get('_auth_user_id')

	all_issues = list(Ticket.objects.filter(user=uid) | Ticket.objects.filter(creator=uid))

	all_issues_table = TicketTable(all_issues)

	context = {

		"session": request.session,
		"all_issues_table": all_issues_table,
	}
	return render(request, "i_tracker/home_table.html", context)

# ISSUE
@login_required(login_url='/login/')
def issue(request, issue_pk = None):

	context = {}

	session = request.session

	uid = session.get('_auth_user_id')

	recived_msgs = get_messages(request)

	# Check if POST or GET
	if request.method == 'POST':

		# Save
		if issue_pk is None:
			form = TicketForm(request.POST)
			print(request.POST)

			if form.is_valid():
				new_issue = form.save(commit=False)
				new_issue.creator = User.objects.get(id=uid)
				new_issue.dateraised = datetime.datetime.now()

				# save data
				form.save()
				messages.success(request, "La incidencia se ha creado correctamente")
			else:

				messages.error(request, "Ha habido un error inesperado, Compruebe que el formulario es correcto.")
				return redirect(request.META['HTTP_REFERER'])

		# Update
		else:
			instance = Ticket.objects.get(pk=issue_pk)
			form = TicketForm(request.POST, instance=instance)
			
			if form.is_valid():
				updated_issue = form.save(commit=False)
			
				# save data
				form.save()
				messages.success(request, "La incidencia se ha actualizado correctamente")
			else:

				messages.error(request, "Ha habido un error inesperado, Compruebe que el formulario es correcto.")
				return redirect(request.META['HTTP_REFERER'])                             

		# return to the home page with message
		return redirect('home')

	else:

		if issue_pk is not None:
			# get the info.
			issue = Ticket.objects.get(pk=issue_pk)
			ticket_form = TicketForm( initial={ 'name'		  : issue.name,
												'description' : issue.description,
												'dateraised'  : issue.dateraised,
												'datesolved'  : issue.datesolved,
												'priority'    : issue.priority,
												'creator'     : issue.creator,
												'categories'  : issue.categories.all(),
												'user'        : issue.user,
												'escalated'	  : issue.escalated,
												'hidden'	  : issue.hidden,
												'state'		  : issue.state,		
												})
			comments = list(Comment.objects.filter(ticket=issue_pk))

			comment_form = CommentForm()
		else:
			# set the default info.
			ticket_form = TicketForm()
			issue = None
			comments = None
			comment_form = None

		profiles = Profile.objects.all()

	context = {

		"TicketForm" 		 : ticket_form,
		"issue"		 		 : issue,
		"session"	 		 : request.session,
		"comments"	 		 : comments,
		"uid"		 		 : uid,
		"CommentForm"		 : comment_form,
		"messages"	 		 : recived_msgs,
		"profiles"	 		 : profiles,
	}


	return render(request, "i_tracker/issue.html", context)

# ISSUE DELETE
@login_required(login_url='/login/')
def delete_issue(request, issue_pk):

	instance = Ticket.objects.get(pk=issue_pk).delete()
	messages.success(request, 'La incidencia se ha eliminado correctamente.')
	return redirect('home')

# COMMENT
@login_required(login_url='/login/')
def comment(request, issue_pk):

	context = {}

	session = request.session

	uid = session.get('_auth_user_id')

	# Check if POST or GET
	if request.method == 'POST':

		# Save
		form = CommentForm(request.POST)
			
		# validate form
		if form.is_valid():
			new_comment = form.save(commit=False)
			new_comment.user = User.objects.get(id=uid)
			new_comment.ticket = Ticket.objects.get(id=issue_pk)
			# save data
			form.save()
			messages.success(request, 'El mensaje se ha guardado correctamente.')
		else:

			messages.error(request, 'Ha habido un error, intentelo de nuevo en unos minutos.')
			return redirect(request.META['HTTP_REFERER'])

	return redirect('issue', issue_pk=issue_pk)

# COMMENT DELETE
@login_required(login_url='/login/')
def delete_comment(request, comment_pk, issue_pk):

	instance = Comment.objects.get(pk=comment_pk).delete()
	messages.success(request, 'El mensaje se ha eliminado correctamente.')
	return redirect(request.META['HTTP_REFERER'])


# RETURN USERS BY PROFILE
@login_required(login_url='/login/')
def get_users_profile(request):

	profile_pk = request.GET.get('profile_pk')

	if  profile_pk == 0:

		result_set = User.objects.all()
	else:

		results = list(UserProfile.objects.filter(profile=profile_pk))

		result_set = []

		for result in results:

			result_set.append(result.user)

	json_response = serializers.serialize('json', result_set, fields=('username'))

	return HttpResponse(json_response, content_type='application/json')

i_tracker/templates/i_tracker/admin_app_name.html
iTracker

i_tracker/templates/i_tracker/base.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

{# Load static files #}
{% load staticfiles %}

<!DOCTYPE html>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>iTracker</title>
        <link rel="shortcut icon" href="{% static 'images/itracker_icono.png' %}" />
        <meta name="description" content="">
        <meta name="author" content="Francesc Bisquerra">
        {% include "i_tracker/head-css.html" %}
        {{ TicketForm.media }}
    </head>

    <body>
        <div class="container-fluid">
        
            {% include "i_tracker/menu.html" %}


            <div class="row">
                <div class="col-sm-10 col-sm-offset-1">
                    {% block content %}{% endblock %}
                </div>
            </div>

            {% include "i_tracker/footer.html" %}

        </div> <!-- container -->

        <!-- scripts -->
        {% include "i_tracker/body-js.html" %}
    </body>
</html>

i_tracker/templates/i_tracker/body-js.html
{% load staticfiles %}

<script type="text/javascript" src="{% static 'js/messages.js' %}"></script>

i_tracker/templates/i_tracker/delete_comment.html
{% extends "i_tracker/base.html" %}
{% load bootstrap3 %}

{% load staticfiles %}

{% block content %}

<div class="row row-top-buffer">
	<div class="row-top-buffer col-sm-4 text-center col-sm-offset-4">

		<div class="page-header">
			<h4>¿ Seguro que desea eliminar el commentario {{ comment_pk }} ?</h4>
			<h6>esta accion no es reversible</h6>
		</div>
		<form method="post">
		  	{% csrf_token %}
			<div class="btn-group">
				<a class="btn btn-default" href="{{ request.META.HTTP_REFERER }}">Volver</a>
				<input class="btn btn-danger" type="submit" value="Eliminar"/>
			</div>
		</form>

	</div>
</div>

{% endblock%}

i_tracker/templates/i_tracker/footer.html
<div class="row">
	<div class="col-md-10">
		<h5><small>iTracker app, todos los derechos reservados*</small></h5>	
	</div>
	<div class="col-sm-2">
		<a class="" href=""><h5><small>about</small></h5></a>
	</div>
</div>

i_tracker/templates/i_tracker/head-css.html
{% load staticfiles %}

<!-- Font awesome -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

<link rel="stylesheet" type="text/css" href="{% static 'css/i_tracker.css'%}">

<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datetimepicker.min.css'%}">

i_tracker/templates/i_tracker/home_table.html
{% extends "i_tracker/base.html" %}
{% load bootstrap3 %}
{% load table_tags %}

{% block content %}

<div class="">
	<div class="col-sm-12">
		<div class="page-header pull-left clickable">
			<h4> Todas las incidencias </h4>
		</div>
	</div>
</div>

{% render_table all_issues_table %}

{% endblock%}

i_tracker/templates/i_tracker/issue.html
{% extends "i_tracker/base.html" %}
{% load bootstrap3 %}
{% load widget_tweaks %}

{% load staticfiles %}

{% block content %}

{% if messages %}
    {% for message in messages %}
    <div class="fade in {% if message.tags %}{{ message.tags }}{% endif %}">
      	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    	{{ message }}
    </div>
    {% endfor %}
{% endif %}

<div class="row row-top-buffer">
	<div class="col-sm-8 text-center col-sm-offset-2">
		<div class="page-header pull-left clickable">
			<h4> Información </h4>
		</div>
	</div>
</div>

<div class="row row-top-buffer">
	<div class="col-sm-8 text-center col-sm-offset-2">

		<form method="post" action="" class=""> {% csrf_token %}

			<div class="row text-left">
				<div class="col-sm-3">
					<label>Creador</label>
					<input type="text" class="form-control" disabled 
							value="{% if issue.creator != None%} {{issue.creator}} {% else %} {{user}} {% endif %}">
				</div>
				<div class="col-sm-6">
					{% bootstrap_field TicketForm.name%}	
				</div>
				<div class="col-sm-3">
					{% bootstrap_field TicketForm.priority%}
				</div>
			</div>

			<div class="row text-left row-top-buffer">
				<div class="col-sm-3">
					<label for="selectProfile">Perfil</label>
					  <select class="form-control" id="selectProfile">
					  	<option value="0">todos</option>
					 	{% for profile in profiles %}
					    <option value="{{profile.pk}}">{{profile.name}}</option>
					  	{% endfor %} 
					  </select>
				</div>
				<div class="col-sm-3">
					{% bootstrap_field TicketForm.user%}
				</div>
				<div class="col-sm-3">
					<label>Emisión</label>
					<input type="text" class="form-control" disabled value="{{issue.dateraised|date:'d/m/Y'}}">
				</div>
				<div class="col-sm-3">
					{% bootstrap_field TicketForm.datesolved%}
				</div>
			</div>

			<div class="row text-left row-top-buffer">
				<div class="col-sm-4">
					{% bootstrap_field TicketForm.categories%}
					<div class="row">
						<div class="col-sm-12">
							<h6>* Para seleccionar más de un valor mantenga la tecla Ctrl presionada.</h6>
						</div>
					</div>
				</div>
				<div class="col-sm-8">
					{% bootstrap_field TicketForm.description%}
				</div>
			</div>

			<div class="row row-top-buffer text-left">

				<div class="col-sm-3">
					{% bootstrap_field TicketForm.state %}
				</div>

				<div class="col-sm-4 col-sm-offset-1">
					<div class="row">
						<div class="col-sm-4">
							<div class="pull-left">
								{% bootstrap_field TicketForm.escalated%}
							</div>
						</div>
						<div class="col-sm-4">
							<div class="pull-left">
								{% bootstrap_field TicketForm.hidden%}
							</div>
						</div>
					</div>
				</div>

				<div class="col-sm-4">
					<div class="btn-group pull-right">
				    	{% if issue.pk != None %}
				    		<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteIssueModal">
				    			Eliminar
				    		</button>
				    	{% endif %}
				    	<input class="btn btn-primary" type="submit" value="Guardar"/>
				    </div>
				</div>
			</div>	
		</form>

	</div>
</div>

<div class="row">
	<div class="col-sm-8 text-center col-sm-offset-2 separator">
	</div>
</div>

{% if issue.pk %}

	<div class="row row-top-buffer">
		<div class="col-sm-8 text-center col-sm-offset-2">
			<div id="issueCommentsLabel" class="page-header pull-left clickable">
				<h4> Comentarios <small>Plegar/desplegar</small></h4>
			</div>
		</div>
	</div>

	<div  class="row">
		<div class="col-sm-8 text-center col-sm-offset-2">
			{% for comment in comments %}

				<div class="issue-comments row row-top-buffer row-bottom-buffer comment-bubble linear-transition">
					<div class="col-md-10">
						<label class="pull-left">{{ comment.user }}:</label>
						<div class="row">
							<div class="col-sm-12">
								<p class="pull-left text-left">{{ comment.description }}</p>
							</div>	
						</div> 
					</div>

					{% if comment.user.pk|stringformat:"s" == uid %}
					<div class="col-md-2">
						<div class="btn-group pull-right">
							<button type="button" class="btn btn-danger" data-toggle="modal" 
									data-target="#deleteCommentModal" data-comment="{{comment.pk}}" 
									data-issue="{{issue.pk}}">
			    				<i class="fa fa-minus"></i>
			    			</button>
						</div>
					</div>
					{% endif %}
				</div>
			
			{% empty %}

				<div class="row-top-buffer row-bottom-buffer">
					<div class="col-md-12">
						<p>No hay commentarios para esta incidencia.</p>
					</div>
				</div>

			{% endfor %}	

			<div class="row-top-buffer row-bottom-buffer">
				<div class="col-md-12">
					<form method="post" action="{% url 'comment' issue_pk=issue.pk %}"> {% csrf_token %}

						<div class="row text-left row-top-buffer">
							<div class="col-sm-12">
								{% bootstrap_form CommentForm%}
							</div>
						</div>

					    <div class="btn-group pull-right">
					    	<input class="btn btn-primary" type="submit" value="Comentar"/>
					    </div>	
					</form>
				</div>
			</div>
		</div>
	</div>

{% endif %}


<!-- Delete issue modal -->

{% if issue.pk != None %}

<div id="deleteIssueModal" class="modal fade" tabindex="-1" role="dialog" >
  	<div class="modal-dialog modal-md">
	    <div class="modal-content">
	    	<div class="modal-header">
			    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			    	<span aria-hidden="true">&times;</span>
			    </button>
			    <h4 class="modal-title" id="gridSystemModalLabel">
			    	¿Esta seguro de que quiere eliminar la incidencia?
			    </h4>
	  		</div>
	  		<div class="modal-body">
	  			<div class="row">
	  				<div class="col-sm-12">
		  				<div class="btn-group pull-right">
							<a class="btn btn-danger" href="{% url 'delete_issue' issue_pk=issue.pk %}">Eliminar</a>
							<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteIssueModal">
								Cancelar
							</button>
						</div>
 					</div>	
	 			</div>
			</div>
    	</div>
  	</div>
</div>

{% endif %}

<!-- Delete comment modal -->

{% if issue.pk != None %}

	<div id="deleteCommentModal" class="modal fade" tabindex="-1" role="dialog" >
	  	<div class="modal-dialog modal-md">
		    <div class="modal-content">
		    	<div class="modal-header">
				    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
				    	<span aria-hidden="true">&times;</span>
				    </button>
				    <h4 class="modal-title" id="gridSystemModalLabel">
				    </h4>
		  		</div>
		  		<div class="modal-body">
		  			<div class="row">
		  				<div class="col-sm-12">
			  				<div class="btn-group pull-right">
								<a class="btn btn-danger">Eliminar</a>
								<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteCommentModal">
									Cancelar
								</button>
							</div>
	 					</div>	
		 			</div>
				</div>
	    	</div>
	  	</div>
	</div>

{% endif %}

<script type="text/javascript">

	$(document).ready (function(){

		$('#deleteCommentModal').on('show.bs.modal', function (event) {

		  var button = $(event.relatedTarget); // Button that triggered the modal
		  var commentId = button.data('comment'); // Extract info from data-* attributes
		  var issueId = button.data('issue'); // Extract info from data-* attributes

		  var url = '/issue/' + issueId + '/comment/delete/' + commentId

		  // Update the modal's content.
		  var modal = $(this);
		  modal.find('.modal-title').text('¿Esta seguro de que quiere eliminar el comentario?');
		  modal.find('.modal-body a').attr("href", url);
		});

        $('#issueCommentsLabel').click(function(e) {

	      $('.issue-comments').toggle("slow", function () {
	        // animation complete
	        $('html, body').animate({
		        scrollTop: $(".issue-comments").offset().top
		    }, 500);
	      });
	    }); 

        $('select#selectProfile').change(function () {

			var optionSelected = parseInt($(this).val());

			$.ajax({
			    url    : '/get/users/profile/',
			    type   : 'GET',
			    data   : ({'profile_pk' : optionSelected}),
			    success: function(result) {

			    	console.log(result)

			        $("#id_user option").remove();

			        $("#id_user").append('<option value>'+ '---------' + '</option>');
					for (var i = result.length - 1; i >= 0; i--) {
						$("#id_user").append('<option value="'+ result[i].pk +'">'+ result[i].fields.username +'</option>');
					};
			    },
			    error: function(error) {
			    	console.log(error)
			    }
			});
		});

	});

</script>

{% endblock %}

i_tracker/templates/i_tracker/login.html
{% extends "i_tracker/base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}


{% block content %}

<div style="padding-top: 100px" class="row">

	<div class="well col-sm-6 col-sm-offset-3">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2">
				<img class="img-responsive" src="{% static 'images/iTracker_logo.png' %}">
			</div>
		</div>
		<div class="row row-top-buffer">
			<div class="col-sm-8 text-center col-sm-offset-2">

				<form method="post" action=""> {% csrf_token %}

				    {% bootstrap_form LoginForm%}

				    <input class="btn btn-primary btn-lg" type="submit" value="Entrar"/>
				</form>

			</div>
		</div>
	</div>

</div>

{% endblock %}

i_tracker/templates/i_tracker/logout.html
youre at logout

i_tracker/templates/i_tracker/menu.html
{% load staticfiles %}

{% if user.is_authenticated %}

<nav class="navbar navbar-default row-top-buffer">
  <div class="">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">
        <img class="iTracker-nav-logo" src="{% static 'images/iTracker_logo.png' %}">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">
          <a href="{% url 'home' %}">
            <i class="fa fa-home fa-lg"></i>
              &nbsp; Home
          </a>
        </li>
        <li class="{% if request.resolver_match.url_name == 'home_table' %}active{% endif %}">
          <a href="{% url 'home_table' %}">
            <i class="fa fa-table fa-lg"></i>
              &nbsp; Vista de tabla
          </a>
        </li>
        <li class="{% if request.resolver_match.url_name == 'issue' and issue == None %}active{% endif %}">
          <a href="{% url 'issue' %}">
            <i class="fa fa-plus fa-lg"></i>
              &nbsp; Nueva incidencia
          </a>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-user fa-lg"></i>&nbsp; {{ user }} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            {% if user.is_superuser %}
              <li><a href="{% url 'admin:index' %}"><i class="fa fa-gears fa-lg"></i>&nbsp; Admin</a></li>
            {% endif %}
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-lg"></i>&nbsp; Salir</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% endif %}

i_tracker/templates/i_tracker/new_issue.html
{% extends "i_tracker/base.html" %}
{% load bootstrap3 %}

{% load staticfiles %}

{% block extrahead %}
  {{ form.media }}
{% endblock %}

{% block content %}

<div class="row row-top-buffer">
	<div class="col-sm-8 text-center col-sm-offset-2">

		<form method="post" action=""> {% csrf_token %}

		    {% bootstrap_form TicketForm%}

		    <input class="btn btn-primary pull-right" type="submit" value="Guardar"/>
		</form>

	</div>
</div>

{% endblock %}